# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Checks

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          sudo apt install libx11-dev libxtst-dev libwayland-dev libxkbcommon-dev
          npm ci
      - name: Run Tests
        run: npm run test

  eslint:
    name: Check ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          sudo apt install libx11-dev libxtst-dev libwayland-dev libxkbcommon-dev
          npm ci
      - name: Run ESLint
        run: npm run lint

  prettier:
    name: Check Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          sudo apt install libx11-dev libxtst-dev libwayland-dev libxkbcommon-dev
          npm ci
      - name: Run Prettier
        run: npm run prettier

  reuse:
    name: Check REUSE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v4
