# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  linux:
    name: Test Deploy for Linux
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: |
          sudo apt install libx11-dev libxtst-dev libwayland-dev libxkbcommon-dev
          npm install
      - name: Create Release
        run: |
          npm run make

  windows:
    name: Test Deploy for Windows
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        # For some reason cmake.js sometimes skips the build step in CI on Windows in this
        # case. So we install and execute cmake.js manually.
        run: |
          npm install cmake-js -g
          npx cmake-js install
          npm install
      - name: Create Release
        run: |
          npm run make

  macos:
    name: Test Deploy for macOS
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      # https://github.com/electron/forge/issues/2807
      - run: python3 -m pip install setuptools --break-system-packages
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: |
          npm install
          npm install appdmg
      - name: Create Release
        run: |
          npm run make
